# Generated by Django 5.1.1 on 2024-09-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], null=True),
        ),
    ]
